FROM ubuntu:18.04
RUN sed -i "s/http:\/\/archive.ubuntu.com/http:\/\/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list && \
    sed -i "s/http:\/\/security.ubuntu.com/http:\/\/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list && \
    dpkg --add-architecture i386 && \
    apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y ssh python libc6-dbg lib32z1 libc-dbg:i386 socat
RUN sed -i -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
    sed -i -e 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/g' /etc/ssh/sshd_config && \
    sed -i -e 's/nullok_secure/nullok/' /etc/pam.d/common-auth && \
    passwd -d root && \
    mkdir /var/run/sshd && \
    ln -s /binary/gdbserver /bin/.