FROM ubuntu:18.04
RUN sed -i "s/http:\/\/archive.ubuntu.com/http:\/\/mirrors.aliyun.com/g" /etc/apt/sources.list && \
    sed -i "s/http:\/\/security.ubuntu.com/http:\/\/mirrors.aliyun.com/g" /etc/apt/sources.list && \
    apt-get update && apt-get -y dist-upgrade
RUN apt-get install -y ssh sshpass gdbserver python libc6-dbg
RUN sed -i -e 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
    sed -i -e 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/g' /etc/ssh/sshd_config && \
    sed -i -e 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
    sed -i -e 's/#PermitEmptyPasswords yes/PermitEmptyPasswords yes/g' /etc/ssh/sshd_config && \
    sed -i -e 's/nullok_secure/nullok/' /etc/pam.d/common-auth && \
    passwd -d root && \
    mkdir /var/run/sshd
